name: Update My README

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bdelanghe/synoptic-github/action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
